# ---- Build stage ----
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Cache deps
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

# Build (note cmd/main.go)
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o server ./cmd/main.go

# ---- Runtime stage ----
FROM alpine:latest

WORKDIR /app

# CA certs (important for HTTPS, DB, APIs)
RUN apk add --no-cache ca-certificates

COPY --from=builder /app/server .

EXPOSE 8080
CMD ["./server"]

