run:
	echo "Running server..."
test:
	echo "Running tests..."
lint:
	echo "Running linter..."
build:
	echo "Building server..."
migrate-up:
	echo "Running migrations..."
migrate-down:
	echo "Running migrations down..."
seed:
	echo "Seeding database..."
