FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download && go mod tidy

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o intelligence ./cmd/main.go

FROM alpine:3.19
RUN apk add --no-cache ca-certificates

WORKDIR /app
RUN apk add --no-cache ca-certificates
RUN apk add --no-cache \
    build-base \
    postgresql-dev \
    python3-dev \
    make
COPY --from=builder /app/intelligence .

EXPOSE 8080
CMD ["./intelligence"]
