services:
  web:
    container_name: carma-web
    image: devlopersabbir/carmasearch-web:latest
    platform: linux/amd64
    profiles:
      - prod
    build:
      context: ../../apps/web
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    env_file:
      - ../../apps/web/.env
    depends_on:
      - server
    networks:
      - carmasearch

  server:
    image: devlopersabbir/carmasearch-server:latest
    platform: linux/amd64
    container_name: carma-server
    profiles:
      - prod
    build:
      context: ../../apps/server
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    env_file:
      - ../../apps/server/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      scraper:
        condition: service_started
    networks:
      - carmasearch

  scraper:
    image: devlopersabbir/carmasearch-scraper:latest
    platform: linux/amd64
    container_name: carma-scraper
    profiles:
      - prod
    build:
      context: ../../apps/scraper
      dockerfile: Dockerfile.scraper
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    env_file:
      - ../../apps/scraper/.env
    networks:
      - carmasearch

  db:
    image: postgres:16-alpine
    container_name: carma_db
    profiles:
      - dev
      - prod
    environment:
      POSTGRES_USER: ${DB_USER:-carma_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-carma0912pass}
      POSTGRES_DB: ${DB_NAME:-carma_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-carma_user} -d ${DB_NAME:-carma_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - carmasearch
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    profiles:
      - dev
      - prod
    ports:
      - "6379:6379"
    networks:
      - carmasearch
    restart: unless-stopped

networks:
  carmasearch:
    driver: bridge

volumes:
  postgres_data:
    driver: local
