FROM python:3.12-slim
WORKDIR /app

RUN apt update && apt install -y \
    build-essential \
    libpq-dev \
    python3-dev \
    make \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt Makefile .
RUN make install
COPY . .
EXPOSE 8000
CMD ["make", "run-prod"]

