name: Server CI

on:
  push:
    branches: [main, dev]
    paths:
      - "apps/server/**"
  pull_request:
    paths:
      - "apps/server/**"

jobs:
  server-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.6

      - name: Application Build test
        run: make server-build
